blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/niceprototypes/nice-react-scroll/discussions
    about: Please use GitHub Discussions for questions and general discussions